import math
import heapq
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.patches import Polygon
from scipy.ndimage import binary_dilation
from random import randrange, choice
import random
import time
def ackermann_path(start, goal, turning_radius=5, step_size=1):
    """
    Generate a list of grid points along a circular arc from start to goal.
    
    This simplistic implementation assumes:
    - start and goal are in grid coordinates (row, col)
    - The vehicle is initially oriented along the line connecting start to goal.
    - The arc is generated with constant curvature corresponding to the turning_radius.
    
    For more accurate Ackermann planning, consider using a Dubins path planner.
    """
    # Convert grid (row, col) to (x,y) where x=col, y=row.
    start_pt = (start[1], start[0])
    goal_pt  = (goal[1], goal[0])
    
    # Compute heading from start to goal.
    dx = goal_pt[0] - start_pt[0]
    dy = goal_pt[1] - start_pt[1]
    heading = math.atan2(dy, dx)
    
    # Compute the total distance (along the chord).
    total_distance = math.hypot(dx, dy)
    
    # Number of steps along the arc.
    num_steps = max(int(total_distance / step_size), 1)
    
    path = []
    # For simplicity, assume a circular arc that spans an angle proportional to the chord length.
    # Calculate the central angle of the arc. In a Dubins curve, the arc length L = R * delta,
    # so delta = L / R. We'll use the chord length as an approximation.
    delta_angle = total_distance / turning_radius
    
    # Determine the center of the circle.
    # The perpendicular to the heading gives the direction toward the circle center.
    # We choose one of the two possible centers arbitrarily.
    center_offset = turning_radius
    center_x = start_pt[0] - center_offset * math.sin(heading)
    center_y = start_pt[1] + center_offset * math.cos(heading)
    
    # Starting angle: angle from center to start.
    start_angle = math.atan2(start_pt[1] - center_y, start_pt[0] - center_x)
    
    # Generate points along the arc.
    for i in range(num_steps + 1):
        t = i / num_steps
        # Interpolate angle along the arc.
        current_angle = start_angle + t * delta_angle
        # Compute point on circle.
        x = center_x + turning_radius * math.cos(current_angle)
        y = center_y + turning_radius * math.sin(current_angle)
        # Convert back to grid coordinates (row, col)
        row = int(round(y))
        col = int(round(x))
        path.append((row, col))
    return path

def ackermann_collision_check(node0, node1, grid, turning_radius=5, step_size=1):
    """
    Check if the curved path between node0 and node1 (generated by ackermann_path)
    is free of obstacles.
    """
    path_points = ackermann_path(node0, node1, turning_radius, step_size)
    for point in path_points:
        row, col = point
        # Check grid boundaries
        if row < 0 or row >= len(grid) or col < 0 or col >= len(grid[0]):
            return False
        if grid[row][col] != 0:
            return False
    return True
def generate_valid_point(size):
    xsize, ysize = size
    return random.randint(0, xsize-1), random.randint(0, ysize-1)
def is_freespace(grid, point):
    if grid[point[0]][point[1]] == 0:
        return True
    return False
def distance(point1, point2):
    x0,y0 = point1
    x1,y1 = point2
    return math.sqrt( ((x1-x0)**2) +((y1-y0)**2))
def basic_line_bresenham(point1, point2):
    x0,y0 = point1
    x1,y1 = point2
    points = []
    dx = abs(x1 - x0)
    dy = abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx - dy
    while True:
        points.append((x0, y0))  # Store the current point
        if x0 == x1 and y0 == y1:  # Stop when we reach the endpoint
            break
        e2 = 2 * err
        if e2 > -dy:
            err -= dy
            x0 += sx
        if e2 < dx:
            err += dx
            y0 += sy

    return points

def line_collision_check(node0, node1, grid):
    line_points = basic_line_bresenham(node0, node1)
    for point in line_points:
        if grid[point[0]][point[1]] != 0:
            return False
        

    return True
def find_nearby(current_node, nodes, radius):
    neighbors = []
    for node in nodes:
        if node == current_node:
            continue
        if distance(current_node, node) <= radius:
            neighbors.append(node)
    return neighbors
def add_edge(graph_edges, node, neighbor, cost):
    if node not in graph_edges:
        graph_edges[node] = []
    graph_edges[node].append((neighbor, cost))
def connect_node_to_graph(node, all_nodes, graph_edges, grid, connection_radius):
    neighbors = find_nearby(node, all_nodes, connection_radius)
    for neighbor in neighbors:
        if ackermann_collision_check(node, neighbor, grid):
            cost = distance(node, neighbor)
            add_edge(graph_edges, node, neighbor, cost)
            add_edge(graph_edges, neighbor, node, cost)
def prm_planner(grid, start, goal, num_samples=1000, connection_radius=20 ):
    # print("Started Planning")
    xsize, ysize = len(grid), len(grid[0])
    size = (xsize, ysize)
    random_nodes = []
    graph_edges = {}
    random_nodes.append(start)
    random_nodes.append(goal)
    while len(random_nodes) < num_samples:
        x,y = generate_valid_point(size)
        if is_freespace(grid, (x,y)):
            random_nodes.append((x,y))
    connect_node_to_graph(start, random_nodes, graph_edges, grid, connection_radius)
    connect_node_to_graph(goal, random_nodes, graph_edges, grid, connection_radius)
    for node in random_nodes:
        neighbors = find_nearby(node, random_nodes, connection_radius)
        for neighbor in neighbors:
            if ackermann_collision_check(node, neighbor, grid):
                cost = distance(node, neighbor)
                add_edge(graph_edges, node, neighbor, cost)
                add_edge(graph_edges, neighbor, node, cost)
    path = astar(graph_edges, start, goal)
    print
    return path, random_nodes, graph_edges
def astar(graph_edges, start, goal):
    open_set = []
    heapq.heapify(open_set)
    count = 0  # Tiebreaker for heap

    g_score = {start: 0}
    f_score = {start: distance(start, goal)}
    came_from = {}

    heapq.heappush(open_set, (f_score[start], count, start))
    visited = set()

    while open_set:
        _, _, current = heapq.heappop(open_set)

        if current == goal:
            # print("Goal reached!")
            return reconstruct_path(came_from, current)

        visited.add(current)

        for neighbor, cost in graph_edges.get(current, []):
            if neighbor in visited:
                continue

            tentative_g = g_score[current] + cost

            if tentative_g < g_score.get(neighbor, float('inf')):
                came_from[neighbor] = current
                g_score[neighbor] = tentative_g
                f_score[neighbor] = tentative_g + distance(neighbor, goal)
                count += 1
                heapq.heappush(open_set, (f_score[neighbor], count, neighbor))

    print("No path found.")
    return []

def reconstruct_path(came_from, current):
    path = [current]
    while current in came_from:
        current = came_from[current]
        path.append(current)
    path.reverse()
    return path
        

def remove_consecutive_duplicates(path):
    if not path:
        return []
    cleaned = [path[0]]
    for point in path[1:]:
        if point != cleaned[-1]:
            cleaned.append(point)
    return cleaned

def generate_continuous_path(sparse_path, grid, turning_radius=5, step_size=0.5):
    """
    Convert a sparse PRM path into a continuous Ackermann-feasible path,
    while checking for collisions with obstacles.
    """
    if not sparse_path or len(sparse_path) < 2:
        return sparse_path

    continuous_path = []
    for i in range(len(sparse_path) - 1):
        start = sparse_path[i]
        end = sparse_path[i + 1]

        # Check if the curved path between them is valid
        if ackermann_collision_check(start, end, grid, turning_radius, step_size):
            segment = ackermann_path(start, end, turning_radius, step_size)
            if continuous_path:
                segment = segment[1:]  # remove duplicate
            continuous_path.extend(segment)
        else:
            # print(f"Skipping segment {start} → {end} due to collision.")
            pass

    return remove_consecutive_duplicates(continuous_path)
        